### ISSUE TITLE
createPortal does not get regenerated on rerender and content disappear

### ISSUE THREAD

**Issue by AlbertSabate** [brisa-build/brisa#315]

**Comment by aralroca** [comment]
@AlbertSabate please can you get more details about this, or a reproducible example to understand it. Thanks

**Comment by AlbertSabate** [comment]
This issue is related with https://github.com/brisa-build/brisa/issues/550. Portal disappear when the second rerender happen on SPA. You have to wait to use portal for the second rerender. Once that issue is fix we should retest this one. Currently Portal becomes very complex to use if you are using SPA.

**Comment by AlbertSabate** [comment]
Because rerender has been fixed this task has been fixed as a part of #550.
