### ISSUE TITLE
Navigate to the same page performs a full reload

### ISSUE THREAD

**Issue by AlbertSabate** [brisa-build/brisa#560]
**Describe the bug**
When you are in page / and have a link to /. This performs a full reload.

**Expected behavior**
Should not do anything? Should only navigate to the top and trigger navigate events?

**Comment by aralroca** [comment]
I think is for this:

https://developer.mozilla.org/en-US/docs/Web/API/NavigateEvent/canIntercept

That is used here:

https://github.com/brisa-build/brisa/blob/9693d60a8dd353f899e4f17cab098243ae123250/packages/brisa/src/utils/rpc/rpc.ts#L111
Many things it does are right and we want them. But it also says this:

> intercept the navigation if only the fragment portion differs.

Before implementing something, it would be good to know what other frameworks do in this case. I also don't see it problematic a normal navigation without SPA in this case, making it do nothing would be worse as user feedback I think. In which cases do you want to navigate to the same page without updating parameters or anything?

**Comment by aralroca** [comment]
Next.js what it does is to scroll up the page and nothing else, nothing is saved to navigation history

**Comment by AlbertSabate** [comment]
My concern of triggering native reload are as follows:

- Unnecessary network usage, some people was concern about cloud services being request based.
- The page flashes.
- Add an unnecessary history (This is based on @aralroca previous message, and I agree)

While it is not very serious issue, and should not be priority, I think we should think in how to make it better. NextJS approach is what I would be expecting.

**Comment by nabby27** [comment]
I've created a [$20 bounty](https://app.opire.dev/issues/01JAPY1VM0NKSW6S8WJBTPDEF9) for someone in the community to solve this issue so you can focus on more important tasks!

**Comment by mobley-trent** [comment]
I'd like to work on this @AlbertSabate

**Comment by aralroca** [comment]
@mobley-trent feel free to PR!

**Comment by AlbertSabate** [comment]
It would be awesome to receive and review your PR. If you need any guidance, feel free to ask on this thread, and we will be doing our best to guide you. :)

**Comment by aralroca** [comment]
I pre-released [0.1.3-canary.1](https://github.com/brisa-build/brisa/releases/tag/0.1.3-canary.1) with this change. Thanks for the contribution @mobley-trent

**Comment by nabby27** [comment]
I've already paid the bounty, congrats @mobley-trent, great job! 👏🏼
