### ISSUE TITLE
onMount won't trigger again when doing SPA

### ISSUE THREAD

**Issue by AlbertSabate** [brisa-build/brisa#581]
**Describe the bug**
When loading a web component with defined onMount, then doing SPA navigation to another page, and come back to the previous page, onMount won't get triggered again.

The bug seems because the component never gets unmounted after changing page?

**To Reproduce**
Pending to add a reproduction @AlbertSabate (Will do this week) and potentially more information about it.

**Expected behavior**
onMount should be triggered every time the component is mounted. Component should be properly unmounted if you navigate using SPA to a page where this component does not exists.

**Comment by aralroca** [comment]
If the web component exists in both pages, it is not dismounted and mounted again, it is the grace to maintain the state of it without being dismounted. This is implemented this way on purpose. This way the layout remains the same after browsing. If you need to dismount and mount it during navigation, you can use a `key` based on the `route`. When the `key` change force the unmount/mounting. But by default, it's not dismounted on purpose.

**Comment by aralroca** [comment]
In the case of a page without the same Web Component should unmount and mount again always.

**Comment by AlbertSabate** [comment]
@aralroca, this is yet unclear where the issue comes from. After more debug it does not seem to come from effects or unMount. It is for that I wrote a note "Pending to add a reproduction @AlbertSabate". Something is off with some code I'm currently debugging and trying to narrow it down. I will use this issue for me to track down tests I did and not to forget. Please ignore it until I can clarify the root issue.

**Comment by AlbertSabate** [comment]
From this code:

```typescript
effect(() => {
    console.log(
      'Im here',
      self.hasAttribute('tabindex'),
      self,
    );
    if (!self.hasAttribute('tabindex')) {
      self.setAttribute('tabindex', '0');
    }
  });
```

When loading the component for first time and second time seems something different.
<img width="446" alt="Screenshot 2024-10-23 at 4 46 38 PM" src="https://github.com/user-attachments/assets/e2957c9c-1730-4d66-9237-961ce183e4a1">

@aralroca why the first time is an object and second an HTMLElement?

**Comment by AlbertSabate** [comment]
Interestingly, the first time appends properly the attr tabindex, but the second time no.

**Comment by AlbertSabate** [comment]
Confirmed unMount and effects it is working as expected.

**Comment by aralroca** [comment]
> From this code:
> 
> ```ts
> effect(() => {
>     console.log(
>       'Im here',
>       self.hasAttribute('tabindex'),
>       self,
>     );
>     if (!self.hasAttribute('tabindex')) {
>       self.setAttribute('tabindex', '0');
>     }
>   });
> ```
> 
> When loading the component for first time and second time seems something different. <img alt="Screenshot 2024-10-23 at 4 46 38 PM" width="446" src="https://private-user-images.githubusercontent.com/2384218/379326059-e2957c9c-1730-4d66-9237-961ce183e4a1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk2OTUyOTksIm5iZiI6MTcyOTY5NDk5OSwicGF0aCI6Ii8yMzg0MjE4LzM3OTMyNjA1OS1lMjk1N2M5Yy0xNzMwLTRkNjYtOTIzNy05NjFjZTE4M2U0YTEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMjNUMTQ0OTU5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YWJjNTU4ZjVkNmEyM2IxN2FhNmZiMjdiYjE2ODA5MTUxOTg0Njc5ZjNmOWQ3ZTYzZGVhNTgyNDEyNDRiNWU4NiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.VxBl_D0Gbt6sbZFzu5al9HK35Sjo3emCKKKvrvGBmtU">
> 
> @aralroca why the first time is an object and second an HTMLElement?

An object? Well, elements are objects, I guess it's something in DevTools that doesn't show it well, but you can use it as an element without problems, right?

**Comment by AlbertSabate** [comment]
I can use it, and it seems properly selecting the DOM, however, it behaves differently the first time appends the setAttribute correctly. The second time does not work. I'm investigating why.

**Comment by AlbertSabate** [comment]
Verified Brisa is working perfect on version 0.1.3.canary.4

**Comment by AlbertSabate** [comment]
Verified Brisa is working perfect on version 0.1.3.canary.4
