### ISSUE TITLE
Server Action in a loop can't pass data

### ISSUE THREAD

**Issue by AlbertSabate** [brisa-build/brisa#631]
**Is your feature request related to a problem? Please describe.**
When you do a loop

```typescript
{response.data
  .map((booking) => (
    <button onClick={(e) => doSomething(e, booking.id)}>lala</button>
))}
```

booking.id will throw an error because it does not exist on the client and the server bookind.id will be undefined.

The very unique way to solve this is injecting a data attr and use dataset to retreive the data on the server.

```typescript
{response.data
  .map((booking) => (
    <button data-lala={booking.id} onClick={doSomething}>lala</button>
))}

// then e.currentTarget.dataset.lala will have the info
```

This is working and is a valid approach, but maybe we could document this or give a better way to handle this situation.

**Comment by aralroca** [comment]
@AlbertSabate is already documented https://brisa.build/building-your-application/data-management/server-actions#using-data-attributes

**Comment by aralroca** [comment]
btw; improve any kind of documentation is always very welcome as a contribution

**Comment by AlbertSabate** [comment]
Ohh nice, I saw the commit https://github.com/brisa-build/brisa/commit/b66b39ba9d4f16b98fd17d3fa8177d21f3eab18b
@aralroca so fast adding docs haha

Let's keep it open for now, maybe someone can improve the examples? If there is no volunteers I'll get more examples there :)

Thank you!!

**Comment by aralroca** [comment]
I am closing the issue since it has been documented. Any PR improving documentation is welcome but you don't need to have an open issue for it.
