### ISSUE TITLE
Client render issues when rendering a select form

### ISSUE THREAD

**Issue by AlbertSabate** [brisa-build/brisa#632]
**Describe the bug**
A option select when setting a default selects another.

![WhatsApp Image 2024-11-15 at 15 09 21](https://github.com/user-attachments/assets/8988234d-f4d9-46a7-bf27-a42769466f19)

**To Reproduce**
I have no idea yet. I know is a regession and I know is something with the changes on version between 0.1.4 to 0.1.5.

**Comment by aralroca** [comment]
What I see:

In the previous canary version of the render fix, it works, then it stops working and always selects the last option in the select. 

When doing a diff of both HTML (the one that worked and the one now), there is no difference, so it is not a problem of the rendered elements.

What has changed is the way these elements are added to the DOM.  Now `selectEl.append(...optionsEl)` is used, while `selectEl.appendChild(optionEl)` was used before.

Before:

https://github.com/brisa-build/brisa/blob/0a3b03539142a637d3d56920e24dbfe1e2409268/packages/brisa/src/utils/brisa-element/index.ts#L325-L330

Now:

https://github.com/brisa-build/brisa/blob/e3a2cda7f07aca3cf840df0712813405926b574c/packages/brisa/src/utils/brisa-element/index.ts#L325-L334

<img width="605" alt="Screenshot 2024-11-17 at 15 50 32" src="https://github.com/user-attachments/assets/236d343d-f542-40a8-b832-72590739f6f7">

However, this works fine...

<img width="1119" alt="Screenshot 2024-11-17 at 16 03 51" src="https://github.com/user-attachments/assets/b09e30cf-a9dd-4ad2-bbf5-75d044a21e48">

I need to do some more research 🤔 any idea what it might be?

**Comment by AlbertSabate** [comment]
Unsure, logic seems correct in both scenarios ... I'm doing more testing in case I can narrow down. I noticed there is an small flash in the DOM. So if you check slow motion first is correct then there is a small almost invisible flash which sets it incorrectly.

**Comment by aralroca** [comment]
I discover that changing:

 ```js
 element.append(...nodes);
 ```
 
 To:
 
 ```js
for (const node of nodes) {
  element.appendChild(node);
}
```

Solves the problem. However, before doing the PR I would like to understand the reason for this and generate the failing test on this particular case. But well, we have already seen the problem... Now I want to understand it! hah

**Comment by aralroca** [comment]
From what I understand: `append` adds all at once and repainted simultaneously, and with the `for`+ `appendChild` does it 1 by 1... What I like more is that the `append` does not make so many operations to the DOM, but at the same time, it generates this problem...

**Comment by aralroca** [comment]
Fixed on https://github.com/brisa-build/brisa/releases/tag/0.1.6-canary.2
