### ISSUE TITLE
Runtime Error: lightningcss module not found after deploying to Vercel

### ISSUE THREAD

**Issue by keita-hino** [brisa-build/brisa#637]
**Describe the bug**
I deployed an application with Tailwind CSS added to Vercel. While the deployment itself was successful, the following runtime error occurred:

```
Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'lightningcss' imported from /var/task/build/brisa.config.js
    at packageResolve (node:internal/modules/esm/resolve:858:9)
    at moduleResolve (node:internal/modules/esm/resolve:931:18)
    at moduleResolveWithNodePath (node:internal/modules/esm/resolve:1173:14)
    at defaultResolve (node:internal/modules/esm/resolve:1216:79)
    at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:542:12)
    at ModuleLoader.resolve (node:internal/modules/esm/loader:510:25)
    at ModuleLoader.getModuleJob (node:internal/modules/esm/loader:239:38)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:96:40)
    at link (node:internal/modules/esm/module_job:95:36) {
  code: 'ERR_MODULE_NOT_FOUND'
}
Node.js process exited with exit status: 1. The logs above can help with debugging the issue.
```

**To Reproduce**

1. Add the Vercel adapter (Reference: https://brisa.build/building-your-application/deploying/vercel)
2. Add Tailwind CSS (Reference: https://brisa.build/building-your-application/integrations/tailwind-css)
3. Deploy the application to Vercel.
4. A runtime error occurs.

The following repository reproduces the error:
[keita-hino/brisa-tailwind-vercel-repro](https://github.com/keita-hino/brisa-tailwind-vercel-repro)

**Expected behavior**
The application should run without any errors.

**Screen recording**
<img width="1726" alt="スクリーンショット 2024-11-19 11 56 31" src="https://github.com/user-attachments/assets/6423d48c-5a08-4f58-b2ed-790a92e95b8b">

**Comment by aralroca** [comment]
Thanks for the reproduction @keita-hino. The problem with `lightningcss` using Tailwind is that it cannot be compiled:

https://github.com/parcel-bundler/lightningcss/issues/701

So it is put as an [external](https://brisa.build/building-your-application/configuring/external) library.

As `.vercel` needs a standalone build without external dependencies for this reason it crashes. But it is incorrect on our part, what we should do is to put the external libraries inside the build.

As a workaround, if you move all the `node_modules` inside `.vercel/output/functions/fn.func/build` it would work, but of course this is not the way to proceed as copying all the modules makes the standalone build huge.

**Comment by aralroca** [comment]
@keita-hino this is solved in [0.1.7-canary.1](https://github.com/brisa-build/brisa/releases/tag/0.1.7-canary.1)  (you need to change `brisa` and also `brisa-tailwindcss` in the same version)

**Comment by keita-hino** [comment]
@aralroca 
Thank you for the quick fix!
I updated `brisa` and `brisa-tailwindcss` to 0.1.7-canary.1 and confirmed that the error has been resolved.
https://github.com/keita-hino/brisa-tailwind-vercel-repro/pull/1

**Comment by aralroca** [comment]
Thanks for the confirmation @keita-hino
