### ISSUE TITLE
Hot Reload does not reload every change

### ISSUE THREAD

**Issue by AlbertSabate** [brisa-build/brisa#640]
**Describe the bug**
Given that I'm a very fast and pro developer and I make changes at light speed, the hot reload can't keep my speed, and therefore I always have multiple hot reload running.

When multiple hot reload are running sometimes not all of them gets triggered or completed (no logs of the last one).
![PHOTO-2024-11-22-10-44-40](https://github.com/user-attachments/assets/5fac7bd3-202a-4182-8d15-5d7ec0fc7625)
3 wait
2 ready
1 missing

**To Reproduce**
Make more than 2 hot reload run at the same time.

**Expected behavior**
- They should run in order and all of them should finish the reload.
- We should cancel previous hot reload and only run the last one.

**Comment by aralroca** [comment]
@AlbertSabate solved in [0.1.7-canary.2](https://github.com/brisa-build/brisa/releases/tag/0.1.7-canary.2) let me know how it goes now! 😊 🔥
