### ISSUE TITLE
panda css example has an error

### ISSUE THREAD

**Issue by aralroca** [brisa-build/brisa#654]
<img width="594" alt="Screenshot 2024-11-30 at 22 07 07" src="https://github.com/user-attachments/assets/19ff190b-aded-4a0a-aa9f-0b9f50644613">

**Comment by aralroca** [comment]
All ok, `bun install` was missing to generate the panda codegen 💪🏽

<img width="611" alt="Screenshot 2024-11-30 at 22 08 30" src="https://github.com/user-attachments/assets/5134cdbe-d2eb-4951-b0c3-b02bd29112f1">

**Comment by artydev** [comment]
The problem is still present when building, indeed all is well with 'bun dev'
