### ISSUE TITLE
Transferred store to the client inconsistency when using -

### ISSUE THREAD

**Issue by AlbertSabate** [brisa-build/brisa#670]
**Describe the bug**
When you have an store key that uses -, this one will work perfectly on the server, but in the client will never arrive.

**To Reproduce**
Just create an store with - and transfer it to the client. You will find that the client map won't have that key.

**Expected behavior**
Should have the key, if this is transferred.

**Comment by aralroca** [comment]
I tried with `some-test` and it works well, how exactly was the store key to reproduce it?

**Comment by AlbertSabate** [comment]
Closing the issue as we've validated that is not a Brisa issue.
